mysql:
  host: localhost
  user: archival_db_user
  password: Mar-1976$$
  database: archival_db
  port: 3306 


mariadb:
  host: localhost
  user: root
  password: Mar-1976
  database: batch_db
  port: 3307

source_base_dir: "C:\\workspace\\testing\\"
dest_base_dir: "C:\\workspace\\testing\\RollingFolders\\"

ignore_dirs:
  - "/clsuser/staging/CAP/CLS/MAPPING_FILES/"
  - "/clsuser/staging/CAP/CLS/BACKUP/"

archival_config_query: "SELECT dir_name, archival_period FROM archival_config"


emaillist:
  Process1:
    email_to: rush2cvmahesh@gmail.com
    email_cc: rush2magilife@gmail.com 
    email_bcc: cvmahesh@rediffmail.com

# folders:
#   folder1:
#     data_folder: "data/folder1"
#     archive_folder: "archive/folder1"
#     delete_folder: "delete/folder1"
#     archive_days: 1   
#     delete_days: 1    

#   folder2:
#     data_folder: "data/folder2"
#     archive_folder: "archive/folder2"
#     delete_folder: "delete/folder2"
#     archive_days: 1  
#     delete_days: 1    
