mysql:
  host: localhost
  user: archival_db_user
  password: Mar-1976$$
  database: archival_db
  port: 3306 


mariadb:
  host: localhost
  user: root
  password: Mar-1976
  database: batch_db
  port: 3307


folders:
  folder1:
    data_folder: "data/folder1"
    archive_folder: "archive/folder1"
    delete_folder: "delete/folder1"
    archive_days: 1   
    delete_days: 1    

  folder2:
    data_folder: "data/folder2"
    archive_folder: "archive/folder2"
    delete_folder: "delete/folder2"
    archive_days: 1  
    delete_days: 1    
